### ISSUE TITLE
Remove public constructor?

### ISSUE THREAD

**Issue by fericit-bostan** [sabomichal/immutable-xjc#10]
Is there a way to suppress the public constructor? I know that by default the no arg constructor is protected but is there a way to make the constructor with arguments be protected or private? The issue is that team members are using the constructor rather than the build that is generated and each time the data type changes the references to the constructor need to be updated. 

This would be a slick option in my opinion. 
Thanks...

**Comment by sabomichal** [comment]
Isn't it easier to instruct your team members to not to use the constructor? The option to not generate the constructor can be added very easily, however I am not really convinced yet.

**Comment by fericit-bostan** [comment]
I agree that the developers should just adhere to the guidelines and that would truly be the simplest solution to the problem. However, since a builder is generated, it does suggest that one should use the builder rather than the constructor in which case it begs the question as to why the constructor exists that is available to the public.
