### ISSUE TITLE
Optional getter and builder generation problematic with primitive integer field

### ISSUE THREAD

**Issue by Badbond** [sabomichal/immutable-xjc#107]
I'm happy to split this into two bug reports, but decided to combine it given one might stumble upon both trying to workaround either.

Using `immutable-xjc:2.0.2`, JAXB 4.0.0, JDK 17.0.7-tem, Maven 3.8.7, Patrodyne's `hisrc-higherjaxb-maven-plugin:2.1.1`.

When generating builders and `Optional` getters for a primitive `xsd:int` type, modelling using `xsd:attribute` or `xsd:element` give unexpected results in the generated class. I'm using flags `-Ximm-builder`, `-Ximm-simplebuildername` and `-Ximm-optionalgetter`. A minimal reproduction case can be found here: https://github.com/Badbond/immutable-xjc-primitive-generation.

The following XSD produces an `Optional` getter, while it shouldn't (it's not nillable):

```xml
    <xsd:complexType name="OptionalForPrimitiveField">
        <xsd:all>
            <!-- Generates Optional<Integer> getter. -->
            <xsd:element name="index" type="xsd:int" nillable="false"/>
        </xsd:all>
    </xsd:complexType>
```

```java
public final class OptionalForPrimitiveField {
    // Ctors, builder, class annotations and Javadoc omitted for brevity.

    private final int index;

    public Optional<Integer> getIndex() {
        return Optional.ofNullable(index);
    }
```

While the following XSD produces a non-compiling class due to a `null` check in the `Builder` on a primitive type:

```xml
    <xsd:complexType name="NullCheckForPrimitiveField">
        <!-- Generates a builder with `null` check for primitive field (compilation error). -->
        <xsd:attribute name="index" type="xsd:int" use="required"/>
    </xsd:complexType>
```

```java
public final class NullCheckForPrimitiveField {
    // Ctors, builder method, class annotations and Javadoc omitted for brevity.
    @XmlAttribute(name = "index", required = true)
    private final int index;

    public int getIndex() {
        return index;
    }


    public static class Builder {
        public NullCheckForPrimitiveField build() {
            if (index == null) { // Compilation error here
                throw new NullPointerException("Required field 'index' have to be assigned a value.");
            }
            return new NullCheckForPrimitiveField(index);
        }
    }
}
```

```
[ERROR] target/generated-sources/xjc/me/soels/model/NullCheckForPrimitiveField.java:[74,23] bad operand types for binary operator '=='
  first type:  int
  second type: <nulltype>
```

**Comment by RoanH** [comment]
It seems like the core issue here is that the concept of (not) being required doesn't really make sense for primitives as they will always be present and have some value. So wrapping them in an optional doesn't really make sense. I'm pushing a change to my PR #125 to effectively start treating primitive values as always required, which should address both of the bugs in this issue.
