### ISSUE TITLE
When JAXB unmarshalls an object members of type list are not immutable.

### ISSUE THREAD

**Issue by Sil0x0000** [sabomichal/immutable-xjc#12]
In the given example the objects that are created by the unmarshalling of xml data does not protect the list from being changed.

[xjc-immutable-test.zip](https://github.com/sabomichal/immutable-xjc/files/484449/xjc-immutable-test.zip)

**Comment by sabomichal** [comment]
Sorry for not replying sooner, this was already fixed in version 1.3.1. Please use the latest version.
