### ISSUE TITLE
Collections are not immutable

### ISSUE THREAD

**Issue by b8b** [sabomichal/immutable-xjc#14]
Defensive copying is missing in
(1) constructor with parameters
(2) copy constructor in builder

It is easy to reproduce:
(1) build an instance i1 with a single item in a list property 
(1) Instantiate a builder with the copy constructor
(2) add an item to the list and build a new instance i2
(3) i1 will have the same 2 elements as i2

---

I have attached a patch to fix it, but the code is not nice:
[defensive_copy.txt](https://github.com/sabomichal/immutable-xjc/files/872926/defensive_copy.txt)

---

From looking at the code, there is another bug introduced in v1.3.1 in the copy constructor. When invoking the getter for a property, it will return an unmodifiable view of a collection that is of no good use for the builder. The patch would also fix that.

(if I understood the code right)

**Comment by sabomichal** [comment]
Patch applied
