### ISSUE TITLE
Copy Constructors do not handle optional parent class properties correctly

### ISSUE THREAD

**Issue by jecede** [sabomichal/immutable-xjc#142]
In the builder constructor the parent's properties are accessed using their getter if '-Ximm-cc' is enabled.
This fails when the property is nullable and '-Ximm-optionalgetter' is enabled.
It tries to assign the optional to the (nullable) field.

I think adding an ".orElse(null)" to these getters would suffice, and will provide a pull request for you to consider.

**Comment by sabomichal** [comment]
Great, thanks for reporting (and fixing).

**Comment by jecede** [comment]
I submitted the pull request. If admitted, could you release it as a bugfix release? That would help me a lot :).

**Comment by sabomichal** [comment]
Closed by #143

**Comment by sabomichal** [comment]
Thanks for the PR, it was just released under v2.0.4 (needs some time to sync to maven central).

**Comment by jecede** [comment]
Thank you very much!
