### ISSUE TITLE
No args constructor with empty lists

### ISSUE THREAD

**Issue by andrievskya** [sabomichal/immutable-xjc#15]
Is it possible to initialize List<> fields in the protected no-args constructor with an empty List<>? 
Maybe with an additional configuration option for this.

**Comment by sabomichal** [comment]
Why it would be needed? The no-arg constructor is there for JAXB to work.

**Comment by andrievskya** [comment]
Yes, we use JAXB to matshal data into class instances from xml data file, and when it doesn't find any element that would  populate the list in question, it just leaves initial value (which turns out to be null). 
When we use these classes later, we have to check for null value instead of just iterating through an empty list.
As far as I can see, JAXB uses reflection to set values of class' fields (as it has no problems with final variables   already set in constructor), so this enhancement should not break it.

**Comment by sabomichal** [comment]
Does this still need to be fixed?

**Comment by andrievskya** [comment]
It seems, that the problem has been fixed,
