### ISSUE TITLE
Publish 1.3.2 release to maven repository

### ISSUE THREAD

**Issue by wandenberg** [sabomichal/immutable-xjc#16]
There are any reason why the version 1.3.2 was not published to [maven repository](https://mvnrepository.com/artifact/com.github.sabomichal/immutable-xjc-plugin) ?
Or is it published in somewhere else?

**Comment by sabomichal** [comment]
Well, as I can see, that version was created by a mistake. There is no change in the code base.

**Comment by wandenberg** [comment]
This is weird @sabomichal because I'm using the version 1.3.1 and when I try to use the `-imm-builder` option I receive this error `unrecognized parameter -immutable -imm-builder`, despite I can see the option on the code on master.
Can you help me to get it work if the code is really on version 1.3.1?
I'm using jaxb2-maven-plugin version 2.3.1 in case this matter.

**Comment by sabomichal** [comment]
I have changed the usage section, it should be configured this way:
`<arguments>
    <argument>-immutable</argument>
    <argument>-imm-builder</argument>
</arguments>`

**Comment by wandenberg** [comment]
Thanks @sabomichal. Now it works ;)
