### ISSUE TITLE
[BUG] -imm-optionalgetter not recognized for XSD

### ISSUE THREAD

**Issue by larscom** [sabomichal/immutable-xjc#39]
Hi,

It seems the optional getter argument is not recognized. Im using the following extensionArgs:
![image](https://user-images.githubusercontent.com/1215195/75487476-b8eddf80-59ae-11ea-910a-61118e609163.png)

Debug info:
![image](https://user-images.githubusercontent.com/1215195/75487308-7debac00-59ae-11ea-9ff5-31eb8d6f9e2a.png)

**Comment by sabomichal** [comment]
This feature is part of the next release version, however the development was done in the master branch so the readme file got updated. It will be fixed with the new release soon.

**Comment by larscom** [comment]
ah great :)

**Comment by mfulgo** [comment]
Any chance you'll publish a release soon? I was excited to use the new feature...

**Comment by sabomichal** [comment]
I have just released the version 1.6.2. It will take some hours till it is synced to maven cetral repository.
