### ISSUE TITLE
Builder does not force setting required fields for XSD

### ISSUE THREAD

**Issue by raginggoblin** [sabomichal/immutable-xjc#40]
When the XSD creates a required field it is still possible to create an object with null through the builder.

E.g. 

![image](https://user-images.githubusercontent.com/1873470/78260875-c68f0b80-74fe-11ea-978b-69e6f34df806.png)
Creates the following Java code:
![image](https://user-images.githubusercontent.com/1873470/78260980-ec1c1500-74fe-11ea-89b8-3f455ca1efe8.png)
It is however still possible to do the following:
TransportDetails.builder().build()
Now all of the fields of my TransportDetails are null. 

Current behaviour: build() function succeeds with null values on required fields
Expected behaviour: build() function should throw an exception

**Comment by sabomichal** [comment]
I somehow missed this open issue. I will take a look on it.
