### ISSUE TITLE
All generated classes are declared final

### ISSUE THREAD

**Issue by jolangloys** [sabomichal/immutable-xjc#41]
Hello,

The plugin generate all classes as final, breaking any class hierarchy generated.

However, very nice work

**Comment by sabomichal** [comment]
I do not see such behavior, only the top level classes are set as final. Can you please provide an example?

**Comment by jolangloys** [comment]
Hello,

Well, I have identified my problem: the generation of the superclass and the classes that inherited it was independant. Therefor, the final modifier was put on the superclass. 

It was due to a bad configuration on my side. However, is it possible to have a parameter to deactivate the use of final class ?

Thanks for your work

**Comment by sabomichal** [comment]
No, there is currently not such parameter. I might add it. Leaving this issue open as an enhancement.
