### ISSUE TITLE
Build new instance from previous instance

### ISSUE THREAD

**Issue by darrint** [sabomichal/immutable-xjc#5]
I have some code that used mutable JAXB objects which needs to be converted. It would smooth the conversion if there was an overloaded builder method for initializing a builder with a previous instance. Example:

    class MyObject {
      private final String prop1;
      private final string prop2;
    
      static MyObjectBuilder myObjectBuilder() {}
      static MyObjectBuilder myObjectBuilder(MyObject myObject) {} // <--- this would help
    
      static class MyObjectBuilder {}
    }

**Comment by victornoel** [comment]
Hi, I would also have the need. I think to have the Builder taking an existing instance as the model would be perfect, and then one could modify some of the fields before calling build().

**Comment by sabomichal** [comment]
Ok, I will add builder copy constructor as an optional feature.

**Comment by sabomichal** [comment]
Fixed in version 1.3
