### ISSUE TITLE
Builder constructor with other object does not set fields from the base class

### ISSUE THREAD

**Issue by gitterrost4** [sabomichal/immutable-xjc#85]
If you have an inheritance-structure and use this plugin to create classes with builders, the builder constructor that initializes the builder with an already present object will not set the fields from the base class of the object.

This can be observed in the generated test classes in `com.github.sabomichal.immutablexjc.test.inheritbuilder.TidyBedroom`. The builder constructor `public Builder(final TidyBedroom o)` does not initialize the field `cost` from the model `Task`.

**Comment by sabomichal** [comment]
Thank you for reporting the bug.

**Comment by gitterrost4** [comment]
I have determined that this only happens with Abstract SuperClasses. I have a fix ready. May I submit a pull request?

**Comment by sabomichal** [comment]
Sure, go ahead.

**Comment by sabomichal** [comment]
Released in 1.7.1 (needs some time to sync with maven-central)
