### ISSUE TITLE
JAXB Constructor newInstance Fails

### ISSUE THREAD

**Issue by ldriscoll** [sabomichal/immutable-xjc#9]
When I use jaxws to perform soap operations, and JAXB tries to create new instances of the objects being sent, I get errors like below:

```
14:54:55.797 [pool-1-thread-1] WARN  o.e.j.u.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.Server@2774c6da: java.lang.IllegalAccessError: Class com.sun.xml.ws.db.glassfish.JAXBRIContextWrapper can not access a member of class com.mysoap.Query with modifiers "protected"
java.lang.IllegalAccessError: Class com.sun.xml.ws.db.glassfish.JAXBRIContextWrapper can not access a member of class com.mysoap.Query with modifiers "protected"
    at com.sun.xml.ws.client.sei.BodyBuilder$DocLit.build(BodyBuilder.java:275) ~[jaxws-rt-2.2.10.jar:2.2.10]
    at com.sun.xml.ws.client.sei.BodyBuilder$JAXB.createMessage(BodyBuilder.java:103) ~[jaxws-rt-2.2.10.jar:2.2.10]
```

**Comment by sabomichal** [comment]
Well this seems to be specific issue with Glassfish com.sun.xml.internal.ws.db.glassfish.JAXBRIContextWrapper. This class seems to really care about illegal constructor access, so it can not instantiate the class with protected constructor. I have to check the implementation if there is any possibility at all to avoid this error.
